// Generated by CoffeeScript 1.8.0
var csv, fs;

csv = require('../js/workflow/Reader');

fs = require('fs');

fs.readFile('data/game.csv', {
  encoding: 'utf8'
}, function(err, data) {
  var count, key, keys, _i, _len;
  if (err) {
    throw err;
  }
  data = csv.parse(data);
  keys = Object.keys(data[0]);
  count = {};
  for (_i = 0, _len = keys.length; _i < _len; _i++) {
    key = keys[_i];
    count[key] = {};
  }
  data.forEach(function(row) {
    var _j, _len1, _results;
    _results = [];
    for (_j = 0, _len1 = keys.length; _j < _len1; _j++) {
      key = keys[_j];
      if (!(row[key] in count[key])) {
        _results.push(count[key][row[key]] = 0);
      } else {
        _results.push(count[key][row[key]]++);
      }
    }
    return _results;
  });
  console.log(data);
  return fs.writeFile('data/data.js', "data=" + (JSON.stringify(data)) + ";\n");
});
