// Generated by CoffeeScript 1.8.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

(function() {
  var Bottombar;
  Bottombar = (function(_super) {
    __extends(Bottombar, _super);

    function Bottombar() {
      return Bottombar.__super__.constructor.apply(this, arguments);
    }

    Bottombar.prototype.init = function(id, title) {
      var titleEl;
      this.id = id;
      this.title = title;
      this.domElement = document.createElement('div');
      this.domElement.id = this.id;
      this.domElement.className = 'bottombar';
      if (this.title) {
        titleEl = document.createElement('h2');
        titleEl.className = 'bottombar-title';
        titleEl.innerText = this.title;
        this.domElement.titleEl = titleEl;
        return this.domElement.appendChild(titleEl);
      }
    };

    return Bottombar;

  })(View);
  this.addBottombar = function(editor) {
    return new Bottombar(editor, _.cid());
  };
  return this.Bottombar = Bottombar;
})();
