// Generated by CoffeeScript 1.8.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

(function() {
  var Editor, root;
  root = this;
  Editor = (function(_super) {
    __extends(Editor, _super);

    function Editor() {
      return Editor.__super__.constructor.apply(this, arguments);
    }

    Editor.prototype.init = function() {
      this.id = 'editor';
      this.domElement = document.createElement('div');
      this.domElement.id = 'editor';
      return this.domElement.className = 'editor';
    };

    return Editor;

  })(View);
  this.addEditor = function() {
    var bottomBar, editor, menubar, sidebar;
    editor = new Editor();
    menubar = addMenubar(editor);
    root.Codeeditor = new CodeEditor(editor);
    sidebar = addSidebar(editor);
    root.TreePanel = new Sidebar.TreePanel(sidebar, _.cid(), Primitives.tree.data);
    new Sidebar.PropPanel(sidebar, _.cid());
    bottomBar = addBottombar(editor);
    root.DataPool = new Bottombar.DataPool(bottomBar, _.cid());
    addViewport(editor);
    return editor;
  };
  return this.Editor = Editor;
})();
