// Generated by CoffeeScript 1.8.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

(function() {
  var Menubar;
  Menubar = (function(_super) {
    __extends(Menubar, _super);

    function Menubar() {
      return Menubar.__super__.constructor.apply(this, arguments);
    }

    Menubar.prototype.init = function(id) {
      this.id = id;
      this.domElement = document.createElement('div');
      this.domElement.id = id;
      return this.domElement.className = 'menubar';
    };

    Menubar.MenuItem = (function(_super1) {
      __extends(_Class, _super1);

      function _Class() {
        return _Class.__super__.constructor.apply(this, arguments);
      }

      _Class.prototype.init = function(id, name) {
        this.id = id;
        this.name = name;
        this.domElement = document.createElement('li');
        this.domElement.id = id;
        this.domElement.className = 'menu-item';
        return this.domElement.innerHTML = name;
      };

      return _Class;

    })(View);

    Menubar.Menu = (function(_super1) {
      __extends(_Class, _super1);

      function _Class() {
        return _Class.__super__.constructor.apply(this, arguments);
      }

      _Class.prototype.init = function(id, name) {
        var list, title;
        this.id = id;
        this.name = name;
        title = document.createElement('span');
        title.id = _.cid();
        title.className = 'menu-title';
        title.innerHTML = name;
        list = document.createElement('ul');
        list.id = _.cid();
        list.className = 'menu-list';
        this.domElement = document.createElement('div');
        this.domElement.id = id;
        this.domElement.className = 'menu';
        this.domElement.titleEl = title;
        this.domElement.appendChild(title);
        this.domElement.listEl = list;
        this.domElement.appendChild(list);
        this.domElement.addEventListener('mouseover', function(e) {
          return this.listEl.className = 'menu-list show';
        });
        return this.domElement.addEventListener('mouseout', function(e) {
          return this.listEl.className = 'menu-list';
        });
      };

      _Class.prototype.add = function(child) {
        this.children[child.id] = child;
        return this.domElement.listEl.appendChild(child.domElement);
      };

      return _Class;

    })(View);

    return Menubar;

  })(View);
  this.addMenubar = function(editor) {
    var addMenu, axis, circle, coordinate, fileMenu, menubar, scatterPlot;
    menubar = new Menubar(editor);
    fileMenu = new Menubar.Menu(menubar, 'file', 'File');
    new Menubar.MenuItem(fileMenu, 'import', 'Import');
    new Menubar.MenuItem(fileMenu, 'export', 'Export');
    addMenu = new Menubar.Menu(menubar, 'add', 'Add');
    coordinate = new Menubar.MenuItem(addMenu, 'group', 'Group');
    coordinate.domElement.addEventListener('click', function(e) {
      return new Group();
    });
    axis = new Menubar.MenuItem(addMenu, 'axis', 'Axis');
    axis.domElement.addEventListener('click', function(e) {
      new Axis();
      if (typeof Renderer !== "undefined" && Renderer !== null) {
        return Renderer.renderAll();
      }
    });
    circle = new Menubar.MenuItem(addMenu, 'circle', 'Circle');
    circle.domElement.addEventListener('click', function(e) {
      new Circle();
      if (typeof Renderer !== "undefined" && Renderer !== null) {
        return Renderer.renderAll();
      }
    });
    scatterPlot = new Menubar.MenuItem(addMenu, 'scatterplot', 'Scatterplot');
    scatterPlot.domElement.addEventListener('click', function(e) {
      new Scatterplot();
      if (typeof Renderer !== "undefined" && Renderer !== null) {
        return Renderer.renderAll();
      }
    });
    return menubar;
  };
  return this.Menubar = Menubar;
})();
