// Generated by CoffeeScript 1.8.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

(function() {
  var Modal;
  Modal = (function(_super) {
    __extends(Modal, _super);

    function Modal() {
      return Modal.__super__.constructor.apply(this, arguments);
    }

    Modal.prototype.init = function(id) {
      this.id = id;
      this.domElement = document.createElement('div');
      this.domElement.id = this.id;
      return this.domElement.className = 'modal';
    };

    Modal.prototype.hide = function() {
      return this.domElement.className = 'modal';
    };

    Modal.prototype.show = function(props) {
      var id, prop;
      for (id in props) {
        prop = props[id];
        new PropRow(this, _cid(), id, prop);
      }
      return this.domElement.className = 'modal show';
    };

    return Modal;

  })(View);
  return this.Modal = Modal;
})();
