// Generated by CoffeeScript 1.8.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

(function() {
  var Viewport;
  Viewport = (function(_super) {
    __extends(Viewport, _super);

    function Viewport() {
      return Viewport.__super__.constructor.apply(this, arguments);
    }

    Viewport.prototype.init = function(id) {
      this.id = id;
      this.domElement = document.createElement('div');
      this.domElement.id = this.id;
      return this.domElement.className = 'viewport';
    };

    return Viewport;

  })(View);
  this.addViewport = function(editor) {
    var height, viewport, width;
    viewport = new Viewport(editor, 'viewport');
    width = window.innerWidth - 250;
    height = window.innerHeight * 0.7 - 30;
    viewport.domElement.width = width;
    viewport.domElement.height = height;
    viewport.domElement.style.width = width + 'px';
    return viewport.domElement.style.height = height + 'px';
  };
  return this.Viewport = Viewport;
})();
