// Generated by CoffeeScript 1.8.0
(function() {
  var Data;
  Data = (function() {
    Data.list = {};

    function Data(key, data) {
      this.data = data;
      Data.list[key] = this.data;
      this.init();
    }

    Data.prototype.init = function() {};

    return Data;

  })();
  if (typeof exports !== "undefined" && exports !== null) {
    return module.exports = Data;
  } else {
    return this.Data = Data;
  }
})();
