// Generated by CoffeeScript 1.8.0
(function() {
  var Reader;
  Reader = {};
  Reader.parse = function(data) {
    var keys, result, rows;
    rows = data.replace(/\n+/g, '\n').replace(/\r+/g, '').trim().split('\n').map(function(row, index) {
      return row.split(',');
    });
    keys = rows.shift();
    result = [];
    rows.forEach(function(row) {
      var _row;
      _row = {};
      row.forEach(function(value, index) {
        return _row[keys[index]] = value;
      });
      return result.push(_row);
    });
    return result;
  };
  Reader.read = function(file, callback) {
    var req;
    req = new XMLHttpRequest;
    req.onload = function() {
      return callback(null, Reader.parse(this.responseText));
    };
    req.open('get', file, true);
    return req.send();
  };
  if (typeof exports !== "undefined" && exports !== null) {
    return module.exports = Reader;
  } else {
    return this.Reader = Reader;
  }
})();
