// Generated by CoffeeScript 1.8.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

(function() {
  var Scatterplot, root;
  Scatterplot = (function(_super) {
    __extends(Scatterplot, _super);

    Scatterplot.counter = 0;

    function Scatterplot(name) {
      var self;
      Scatterplot.__super__.constructor.call(this);
      self = this;
      this.xAxis = new Axis('x axis');
      this.yAxis = new Axis('y axis');
      this.point = new Circle('point');
      this.yAxis.prop.rotate.value = 90;
      this.yAxis.prop.y.value = 100;
      this.yAxis.prop.range.value = [10, 0];
      _.extend(this.prop, {
        pointData: {
          name: 'Point data',
          type: 'select',
          value: null,
          set: function() {
            var key, result, value, _ref;
            result = [
              {
                name: 'none',
                value: null
              }
            ];
            _ref = Data.list;
            for (key in _ref) {
              value = _ref[key];
              result.push({
                name: key,
                value: key
              });
            }
            return result;
          },
          listener: function(value) {
            self.prop.pointData.value = value;
            self.point.bind(value);
            return self.updateChildren();
          }
        },
        xAxis: {
          name: 'X axis',
          type: 'select',
          value: null,
          set: function() {
            var data, dataName, key, result, _ref;
            result = [
              {
                name: 'none',
                value: null
              }
            ];
            _ref = Data.list;
            for (dataName in _ref) {
              data = _ref[dataName];
              for (key in data[0]) {
                result.push({
                  name: "" + dataName + "." + key,
                  value: JSON.stringify([dataName, key])
                });
              }
            }
            return result;
          },
          listener: function(value) {
            if (value === 'null') {
              self.prop.xAxis.value = null;
            } else {
              self.prop.xAxis.value = value;
            }
            return self.updateChildren();
          }
        },
        yAxis: {
          name: 'Y axis',
          type: 'select',
          value: null,
          set: function() {
            var data, dataName, key, result, _ref;
            result = [
              {
                name: 'none',
                value: null
              }
            ];
            _ref = Data.list;
            for (dataName in _ref) {
              data = _ref[dataName];
              for (key in data[0]) {
                result.push({
                  name: "" + dataName + "." + key,
                  value: JSON.stringify([dataName, key])
                });
              }
            }
            return result;
          },
          listener: function(value) {
            if (value === 'null') {
              self.prop.yAxis.value = null;
            } else {
              self.prop.yAxis.value = value;
            }
            return self.updateChildren();
          }
        },
        width: {
          name: 'Width',
          type: 'number',
          value: 300,
          listener: function(value) {
            self.prop.width.value = value;
            return self.updateChildren();
          }
        },
        height: {
          name: 'Height',
          type: 'number',
          value: 150,
          listener: function(value) {
            self.prop.height.value = value;
            return self.updateChildren();
          }
        }
      });
      this.setCode();
      this.updateChildren();
      Primitives.tree.changeParent(this.xAxis, this.id);
      Primitives.tree.changeParent(this.yAxis, this.id);
      Primitives.tree.changeParent(this.point, this.id);
      TreePanel.select(this.treeNode);
    }

    Scatterplot.prototype.init = function(name) {
      this.type = 'scatterplot';
      return this.name = name || 'Scatterplot ' + Scatterplot.counter++;
    };

    Scatterplot.prototype.updateChildren = function() {
      var step, xColumn, xDomain, xMax, xMin, yColumn, yDomain, yMax, yMin;
      this.xAxis.prop.length.value = this.prop.width.value;
      this.yAxis.prop.length.value = this.prop.height.value;
      this.yAxis.prop.y.value = this.prop.height.value;
      this.xAxis.prop.domain.value = this.prop.xAxis.value;
      this.yAxis.prop.domain.value = this.prop.yAxis.value;
      if (this.prop.xAxis.value) {
        xDomain = this.prop.xAxis.value;
        if (_.isType(xDomain, 'String')) {
          xDomain = JSON.parse(xDomain);
        }
        xColumn = Data.list[xDomain[0]].map(function(row) {
          var e;
          try {
            return parseFloat(row[xDomain[1]]);
          } catch (_error) {
            e = _error;
            return 0;
          }
        });
        xMax = Math.max.apply(this, xColumn);
        xMin = Math.min.apply(this, xColumn);
        if (xMin >= 0) {
          this.xAxis.prop.range.value = [0, xMax];
          this.point.prop.x.value = "$data['" + xDomain[1] + "'] / " + xMax + " * " + this.prop.width.value;
          this.yAxis.prop.x.value = 0;
        } else {
          this.xAxis.prop.range.value = [xMin, xMax];
          step = this.prop.width.value / (xMax - xMin);
          this.point.prop.x.value = "$data['" + xDomain[1] + "'] * " + step + " + " + (-xMin * step);
          this.yAxis.prop.x.value = "" + (-xMin * step);
        }
      }
      if (this.prop.yAxis.value) {
        yDomain = this.prop.yAxis.value;
        if (_.isType(yDomain, 'String')) {
          yDomain = JSON.parse(yDomain);
        }
        yColumn = Data.list[yDomain[0]].map(function(row) {
          var e;
          try {
            return parseFloat(row[yDomain[1]]);
          } catch (_error) {
            e = _error;
            return 0;
          }
        });
        yMax = Math.max.apply(this, yColumn);
        yMin = Math.min.apply(this, yColumn);
        if (yMin >= 0) {
          this.yAxis.prop.range.value = [yMax, 0];
          this.point.prop.y.value = "$data['" + yDomain[1] + "'] / " + yMax + " * " + this.prop.height.value;
          this.xAxis.prop.y.value = 0;
        } else {
          this.yAxis.prop.range.value = [yMax, yMin];
          step = this.prop.height.value / (yMax - yMin);
          this.point.prop.y.value = "$data['" + yDomain[1] + "'] * " + step + " + " + (-yMin * step);
          this.xAxis.prop.y.value = "" + (-yMin * step);
        }
      }
      return Renderer.renderAll();
    };

    return Scatterplot;

  })(Primitive);
  if (typeof exports !== "undefined" && exports !== null) {
    root = exports;
  } else {
    root = this;
  }
  return _.extend(root, {
    Scatterplot: Scatterplot
  });
})();
